name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  composer-project:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        php: [8.1, 8.2, 8.3]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: template-project

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Create Drupal project
        run: |
          composer create-project php-tuf/drupal-project --repository '{"type": "path", "url": "template-project", "options": {"symlink": false}}' --stability=dev -vvv

      - name: Install modules and themes
        run: composer -vvv require drupal/address drupal/antibot drupal/automatic_updates drupal/coffee drupal/diff drupal/easy_breadcrumb drupal/eca drupal/focal_point drupal/geocoder drupal/geofield drupal/gin drupal/gin_toolbar drupal/honeypot drupal/leaflet_more_maps drupal/linkit drupal/media_entity_download drupal/media_file_delete drupal/metatag drupal/pathauto drupal/project_browser drupal/quick_node_clone drupal/redirect drupal/sam drupal/scheduler drupal/simple_sitemap drupal/smart_date drupal/type_tray drupal/uli_custom_workflow drupal/webform
        working-directory: drupal-project

      - name: Update Drupal core
        run: composer -vvv require drupal/core-recommended:^10 drupal/core-composer-scaffold:^10 --update-with-all-dependencies
        working-directory: drupal-project

      - name: Archive cached TUF metadata
        uses: actions/upload-artifact@v4
        with:
          name: tuf-cache--php-${{ matrix.php }}
          path: drupal-project/vendor/composer/tuf
